# Generated by Django 6.0.5 on 2026-06-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_badge_studentbadge_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
