# Generated by Django 6.0.5 on 2026-06-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
    ]
