# Generated by Django 6.0.5 on 2026-06-19 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('code_snippet', models.TextField(blank=True)),
                ('example_output', models.TextField(blank=True)),
                ('practice_activity', models.TextField(blank=True, help_text='Small task for the learner.')),
                ('documentation_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('estimated_minutes', models.PositiveIntegerField(default=5)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='my_app.learningmodule')),
            ],
        ),
    ]
