# Generated by Django 6.0.5 on 2026-06-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_learningmodule_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='subject',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JavaScript')], default='HTML', max_length=10),
        ),
    ]
