# Generated by Django 6.0.5 on 2026-06-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_learningmodule_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmodule',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='image',
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='order',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='estimated_minutes',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
    ]
