# Generated by Django 6.0.5 on 2026-06-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_remove_learningmodule_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyresult',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='historyresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.quiz'),
        ),
    ]
