# Generated by Django 6.0.5 on 2026-06-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_quizfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfeedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
