# Generated by Django 6.0.5 on 2026-06-24 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizfeedback',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='my_app.historyresult'),
        ),
        migrations.AlterUniqueTogether(
            name='quizfeedback',
            unique_together={('history', 'teacher')},
        ),
    ]
